import './assets/scss/all.scss';
import 'bootstrap/dist/js/bootstrap.min.js';
import './layout/header';
import './pages/5-1_booking.js';
import './pages/5-1-1_booking.js';
import './pages/4_menu.js';
import './pages/_register.js';
import './pages/_login.js';
// console.log('Hello world!!!');
// console.log('Hello world*2!!!');
// console.log('成功加入');
